### ISSUE TITLE
Router错误，RouteMap没有覆盖

### ISSUE THREAD

**Issue by trycat110** [iamyours/Wandroid#2]
加载Router映射错误，是不是库有问题

**Comment by iamyours** [comment]
库应该是没有问题的，具体日志看下

**Comment by defalt1996** [comment]
Update: The apk you release is fine, but project we build then install on device will crash caused by this issue. Could you please advise?

Hey, this application is amazing, but I got same issue. Please advise:

Here I attached part of logs:
`--------- beginning of crash
2019-09-17 10:28:15.581 21743-21743/io.github.iamyours.wandroid E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.iamyours.wandroid, PID: 21743
    java.lang.RuntimeException: 加载Router映射错误！
        at io.github.iamyours.router.RouteMap.loadInto(RouteMap.java:7)
        at io.github.iamyours.router.ARouter.init(ARouter.java:21)
        at io.github.iamyours.router.ARouter.getInstance(ARouter.java:15)
        at io.github.iamyours.wandroid.util.RouterUtil.navWeb(RouterUtil.kt:19)
        at io.github.iamyours.wandroid.util.RouterUtil.navWeb$default(RouterUtil.kt:13)
        at io.github.iamyours.wandroid.adapter.ArticleAdapter$initView$1.onClick(ArticleAdapter.kt:35)
        at android.view.View.performClick(View.java:6608)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:785)
        at android.view.View$PerformClick.run(View.java:25921)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6867)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
2019-09-17 10:28:15.587 578-578/? E/SELinux: avc:  denied  { find } for service=miui.mqsas.MQSService pid=21743 uid=10595 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:mqs_service:s0 tclass=service_manager permissive=0
2019-09-17 10:28:15.588 21743-21743/io.github.iamyours.wandroid E/MQSEventManagerDelegate: failed to get MQSService.
2019-09-17 10:28:15.592 1771-1804/? W/ActivityManager:   Force finishing activity io.github.iamyours.wandroid/.MainActivity
2019-09-17 10:28:15.592 3040-3081/? I/octvm_klo: klo lock
2019-09-17 10:28:15.595 15961-15973/? D/Launcher: get showing item successandroid.graphics.Bitmap@a0a5ca8
2019-09-17 10:28:15.595 1771-1804/? D/ActivityTrigger: ActivityTrigger activityPauseTrigger 
2019-09-17 10:28:15.596 738-3099/? E/ANDR-PERF-MPCTL: poll() has timed out for /sys/module/msm_performance/events/cpu_hotplug
2019-09-17 10:28:15.596 738-3099/? E/ANDR-PERF-MPCTL: Block on poll()`

Is there anything need to configure?

**Comment by iamyours** [comment]
@defalt1996 看下gradle编译日志是否有以下路由映射打印
```
> Task :app:checkDebugDuplicateClasses

> Task :app:transformClassesWithRouterTransformForDebug
route map:[/collect:io.github.iamyours.wandroid.ui.collect.CollectListActivity, /web:io.github.iamyours.wandroid.ui.web.WebActivity, /search:io.github.iamyours.wandroid.ui.search.SearchActivity, /history:io.github.iamyours.wandroid.ui.history.HistoryArticleListActivity, /login:io.github.iamyours.wandroid.ui.login.LoginActivity]
===========route transform finished:539

> Task :app:transformClassesWithDexBuilderForDebug
```

**Comment by iamyours** [comment]
路由框架使用的是[https://github.com/iamyours/SimpleRouter](https://github.com/iamyours/SimpleRouter),[基于Transform api实现](https://juejin.im/post/5cf35bde6fb9a07ed440e99a)的，正常编译成功后，会替换`RouteMap`类,生成如下代码：
```
public class RouteMap {
    public RouteMap() {
    }

    void loadInto(Map<String, String> var1) {
        var1.put("/collect", "io.github.iamyours.wandroid.ui.collect.CollectListActivity");
        var1.put("/web", "io.github.iamyours.wandroid.ui.web.WebActivity");
        var1.put("/search", "io.github.iamyours.wandroid.ui.search.SearchActivity");
        var1.put("/history", "io.github.iamyours.wandroid.ui.history.HistoryArticleListActivity");
        var1.put("/login", "io.github.iamyours.wandroid.ui.login.LoginActivity");
    }
}
```

**Comment by mashihao** [comment]
好像并没有生成

**Comment by iamyours** [comment]
@mashihao 看下编译gradle日志，是否有
```
route transform finished:xxx 
```

**Comment by trumeen** [comment]
> @mashihao 看下编译gradle日志，是否有
> 
> ```
> route transform finished:xxx 
> ```

我这边也遇到了这个问题，我看日志里面是由这句话打印的。但是没有生成RouteMap 这个类。

> Task :app:transformClassesWithRouterTransformForDebug
route map:[/collect:io\github\iamyours\wandroid\ui\collect\CollectListActivity, /history:io\github\iamyours\wandroid\ui\history\HistoryArticleListActivity, /login:io\github\iamyours\wandroid\ui\login\LoginActivity, /search:io\github\iamyours\wandroid\ui\search\SearchActivity, /web:io\github\iamyours\wandroid\ui\web\WebActivity]
===========route transform finished:1806

**Comment by liyao20190808** [comment]
同样遇到了，跳转页面时会crash掉

**Comment by iamyours** [comment]
已修复，更新下router-plugin版本号。
```
classpath 'io.github.iamyours:router-plugin:1.0.2'
```
问题见SimpleRouter项目的[issue #3](https://github.com/iamyours/SimpleRouter/issues/3)

**Comment by liyao20190808** [comment]
> 已修复，更新下router-plugin版本号。
> 
> ```
> classpath 'io.github.iamyours:router-plugin:1.0.2'
> ```
> 
> 问题见SimpleRouter项目的[issue #3](https://github.com/iamyours/SimpleRouter/issues/3)

 dependencies {
        classpath 'com.android.tools.build:gradle:3.4.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'io.github.iamyours:router-plugin:1.0.2'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
还是会crash额，看起来要跳转到的explicit activity名称有问题
2019-10-09 11:02:50.018 22324-22324/io.github.iamyours.wandroid E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.iamyours.wandroid, PID: 22324
    android.content.ActivityNotFoundException: Unable to find explicit activity class {io.github.iamyours.wandroid/**iogithubiamyourswandroiduiwebWebActivity**}; have you declared this activity in your AndroidManifest.xml?
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1933)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1748)
        at android.app.Activity.startActivityForResult(Activity.java:5168)
        at android.app.Activity.startActivityFromFragment(Activity.java:5144)
        at android.app.Activity$HostCallbacks.onStartActivityFromFragment(Activity.java:7690)
        at android.app.Fragment.startActivityForResult(Fragment.java:1095)
        at android.app.Fragment.startActivityForResult(Fragment.java:1084)
        at io.github.iamyours.router.Postcard.navigation(Postcard.java:74)
        at io.github.iamyours.router.Postcard.navigation(Postcard.java:79)
        at io.github.iamyours.wandroid.util.RouterUtil.navWeb(RouterUtil.kt:21)
        at io.github.iamyours.wandroid.util.RouterUtil.navWeb$default(RouterUtil.kt:13)
        at io.github.iamyours.wandroid.adapter.ArticleAdapter$initView$1.onClick(ArticleAdapter.kt:35)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by iamyours** [comment]
应该是不同操作系统的文件路径分隔符不同产生的bug，这边新传了一个版本`1.0.3`，你先试下。我这边是mac os，如果还是闪退等晚上我用windows调试解决。

**Comment by liyao20190808** [comment]
> 应该是不同操作系统的文件路径分隔符不同产生的bug，这边新传了一个版本`1.0.3`，你先试下。我这边是mac os，如果还是闪退等晚上我用windows调试解决。

感谢owner，尝试了‘1.0.3’版本，编译时抛出如下日志：
java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
	at java.util.regex.Pattern.error(Pattern.java:1957)
	at java.util.regex.Pattern.compile(Pattern.java:1704)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at java.lang.String.replaceAll(String.java:2223)
	at java_lang_String$replaceAll.call(Unknown Source)
	at io.github.iamyours.transform.RouterTransform.getClassName(RouterTransform.groovy:223)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:352)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
	at io.github.iamyours.transform.RouterTransform$_readClassWithPath_closure1.doCall(RouterTransform.groovy:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:411)
	at groovy.lang.Closure.call(Closure.java:427)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.eachFileRecurse(ResourceGroovyMethods.java:1283)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.eachFileRecurse(ResourceGroovyMethods.java:1281)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.eachFileRecurse(ResourceGroovyMethods.java:1281)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.eachFileRecurse(ResourceGroovyMethods.java:1518)
	at org.codehaus.groovy.runtime.dgm$991.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:246)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at io.github.iamyours.transform.RouterTransform.readClassWithPath(RouterTransform.groovy:167)
	at io.github.iamyours.transform.RouterTransform$readClassWithPath$1.callCurrent(Unknown Source)
	at io.github.iamyours.transform.RouterTransform.transform(RouterTransform.groovy:64)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:47)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:284)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:273)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:258)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:67)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:145)
	at org.gradle.internal.execution.impl.steps.ExecuteStep.execute(ExecuteStep.java:49)
	at org.gradle.internal.execution.impl.steps.CancelExecutionStep.execute(CancelExecutionStep.java:34)
	at org.gradle.internal.execution.impl.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:69)
	at org.gradle.internal.execution.impl.steps.TimeoutStep.execute(TimeoutStep.java:49)
	at org.gradle.internal.execution.impl.steps.CatchExceptionStep.execute(CatchExceptionStep.java:33)
	at org.gradle.internal.execution.impl.steps.CreateOutputsStep.execute(CreateOutputsStep.java:50)
	at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:43)
	at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:29)
	at org.gradle.internal.execution.impl.steps.CacheStep.executeWithoutCache(CacheStep.java:134)
	at org.gradle.internal.execution.impl.steps.CacheStep.lambda$execute$3(CacheStep.java:83)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:82)
	at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:36)
	at org.gradle.internal.execution.impl.steps.PrepareCachingStep.execute(PrepareCachingStep.java:33)
	at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:38)
	at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:23)
	at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
	at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
	at java.util.Optional.map(Optional.java:215)
	at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:52)
	at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:34)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:119)
	at org.gradle.api.internal.tasks.execution.ResolvePreviousStateExecuter.execute(ResolvePreviousStateExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:93)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:45)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:94)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:67)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:315)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:305)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:101)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)

**Comment by iamyours** [comment]
`1.0.4`版本在windows环境下已经适配测试成功，感谢 @liyao20190808 测试。
