### ISSUE TITLE
文章详情页往下滑动闪退(必现),其他tab切换“我的” 出现Fragment重叠（必现）

### ISSUE THREAD

**Issue by zzzsssbo** [iamyours/Wandroid#5]
小米手机 系统android10
app是通过你的掘金文章里的下载链接下载的。

**Comment by iamyours** [comment]
不知道你打开的是否是简书文章，尝试复现了下，估计是以下错误，简书文章重定向了，已修复，可以clone代码安装
```
 java.lang.IllegalArgumentException: unexpected url: jianshu://notes/ea370b6fca40
at okhttp3.Request$Builder.url(Request.java:143)
at io.github.iamyours.wandroid.util.Wget.head(Wget.kt:42)
```
